Fix missing forward class declaration
Building iOS static libraries with a generated .cpp file containing:
#include <cppmicroservices/BundleImport.h>
CPPMICROSERVICES_BUNDLE_IMPORT(%BUNDLE_NAME%)

produces the following error:

error: no type named 'BundleContextPrivate' in namespace 'cppmicroservices


Signed-off-by: The MathWorks, Inc. Roy.Lurie@mathworks.com