Fix compiler errors
Implement operator<< to resolve valgrind warnings about un-initialized data due to the compiler padding the structs used for parameterized tests.

Fix VS 2015 compiler error: error C2440: 'initializing': cannot convert from 'initializer list' to 'cppmicroservices::scrimpl::RefChangeNotification'